--
version: "3.4"

services:
    postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "jkzomaar"
      POSTGRES_USER: "jkzomaar"
      POSTGRES_PASSWORD: "secret"
      TZ: "Europe/Brussels"
    ports:
      - 5432:5432
    healthcheck:
      test:
        - "CMD"
        - "pg_isready"
        - "-d"
        - "jkzomaar"
        - "-U"
        - "jkzomaar"
      timeout: 30s
      interval: 10s
      retries: 10
